### PR TITLE
Add convenience method Controller.getContext()

### PR DESCRIPTION
**Pull request by cachapa**
Reduces the effort when migrating from Fragments

I recently migrated a project which was heavily using fragments, and it was a (in my opinion unnecessary) pain to go through all of my fragments and replacing getContext calls with getActivity.

### CODE REVIEW

**Comment by sockeqwe** [comment]
Imho this is not an API improvement of a controller. In fact, this will add more confusion as now you can call `getActivity()` or `getContext()`. 

Regarding migrating: with Android Studio you can do find / replace in path which does renaming from getContext() to getActivity() very easy and convenient.
Otherwise, one could create its own controller base class providing a `getContext()` method delegating to `getActivity()` and then use this base controller class instead of plain Controller class. 

Adding getContext () makes Controller's API unnecessary verbose  for sake of "easier migrating from fragments".

**Comment by cachapa** [comment]
Blindly performing find/replace on your code can be dangerous, especially if you're replacing getContext with getActivity since in some cases you can introduce subtle bugs (e.g. getContext on a themed fragment is different from getActivity).

I understand the concern with making the API unnecessarily verbose, but I think in this case it's justified by the fact that replacing fragments is one of this library's main use cases.

**Comment by PaulWoitaschek** [comment]
Its great to keep the API clean. Why create unnecessary legacy code? Add it as a base class if you really need it. Every method less makes the API easier to understand. Especially if it's a duplicate method.

**Comment by cachapa** [comment]
I don't think there's much confusion between getActivity and getContext. The problem doesn't exist in fragments either since you get the object you need for your use (say, layoutInflater requires a context object whereas you can only call finish() on an Activity).

It's actually specialised knowledge that an Activity is a Context object. Granted, every Android dev knows that, but it's not clear just looking at the API.

**Comment by cachapa** [comment]
@PaulWoitaschek I'm fine with going over the code and replacing getContext with getActivity calls.
As I said, I understand the concerns even if in this case I think it would be justified in making Controllers (more of) a drop-in replacement for Fragments.

**Comment by EricKuck** [comment]
While I appreciate the idea of reducing friction when transitioning from Fragments to Controllers, a goal of this library needs to be having a clear API, not being a drop-in replacement to what people were using before. As others have mentioned, `getActivity()`and `getApplicationContext()` already exist for the use of getting a context. If this is useful to some, by all means make a `BaseController` that includes a `getContext()` method!

**Pull request closed without merging**
