### PR TITLE
Fix MainActivity from leaking by releasing the listeners kept by handler

### PR DESCRIPTION
**Pull request by xxfast**
This fixes the leak mentioned in #500

### CODE REVIEW

**Comment by svenjacobs** [comment]
@EricKuck Could this please be merged and rolled out in a bugfix release?

**Review by EricKuck — APPROVED** [review]

**Comment by EricKuck** [comment]
Nice one, thanks!

**Comment by PaulWoitaschek** [comment]
This code is not properly formatted. What about defining a code style and enforcing it on ci builds? @EricKuck

**Comment by svenjacobs** [comment]
@EricKuck Could you please release a bugfix version containing this fix? Many thanks!

**Pull request merged**
