### PR TITLE
Expose parent constructor with Bundle as parameter

### PR DESCRIPTION
**Pull request by luizgrp**
Expose constructor of parent class with Bundle as parameter in LifecycleController.

### CODE REVIEW

**Comment by EricKuck** [comment]
Great catch. I don't think there's a reason to move `lifecycleRegistryOwner`'s initialization into the constructor though. Can you move that back to where it was and just call `super` from both constructors?

**Comment by luizgrp** [comment]
I agree, done 👍 
To be honest I had just followed a "pattern" I saw [here](https://github.com/bluelinelabs/Conductor/blob/09df937c8825bffefba935480df8ce5780dc1737/conductor-modules/rxlifecycle2/src/main/java/com/bluelinelabs/conductor/rxlifecycle2/RxController.java) (initialization of the class variable into the constructor and constructor without parameters calling the other one).

**Comment by luizgrp** [comment]
By the way, thanks for this amazing library!

**Comment by EricKuck** [comment]
Haha I didn't notice I did it the other way in the lifecycle module. I'll change that. Thanks for the contribution!

**Comment by PaulWoitaschek** [comment]
It's now inconsistent with `LifecycleRestoreViewOnCreateController`

**Pull request merged**
