### PR TITLE
add rxlifecycle2 support, fixes #148

### LINKED ISSUE #148: RxJava 2 support
It would be great to have RxJava2 support.

### PR DESCRIPTION
**Pull request by burntcookie90**
Just putting this here for now. Should be mergable once RxAndroid and RxLifecycle come out of snapshot

### CODE REVIEW

**Comment by burntcookie90** [comment]
https://github.com/trello/RxLifecycle/releases/tag/v2.0 we're live! I'll push an update to remove snapshots tonight

**Comment by EricKuck** [comment]
🎉

**Comment by burntcookie90** [comment]
should be good, take it for a whirl and let me know how it is

**Comment by EricKuck** [comment]
Looks great, thanks!

**Pull request merged**
