### PR TITLE
Implement DialogController

### PR DESCRIPTION
**Pull request by MkhytarMkhoian**
Implement DialogController like DialogFragment
I already have this code in production and its work like a charm

### CODE REVIEW

**Comment by EricKuck** [comment]
This looks really well done, and I'll probably be using it myself in future projects. I'm not sure it belongs in the core project though, as it's kind of ancillary to the intent of the library. What do you think of publishing it as your own library? I'd be happy to link to it from the main readme of this project.

**Comment by MkhytarMkhoian** [comment]
I think it's a good idea. I will write here when I'm done.

**Comment by MkhytarMkhoian** [comment]
@EricKuck I'm done

https://github.com/MkhytarMkhoian/ConductorDialog

`implementation 'com.github.mkhytarmkhoian:conductor-dialog:1.0.0'`

**Comment by mradzinski** [comment]
@MkhytarMkhoian Hey! Thanks for your PR. What's the immediate advantage of this over showing a standard alert dialog or using #248? Not saying it's bad or anything (actually looks really well done! Kudos to you!), just wondering the reasons behind the PR so I can choose to use your library. Thanks 👍

**Comment by PaulWoitaschek** [comment]
It handles state restoring and integrates with the rest of conductor for targetController etc.

**Comment by MkhytarMkhoian** [comment]
@mradzinski Hi! When you show a standard alert dialog, you don't have this dialog in you back stack. One of a case, when you turn on/off screen, your dialog is gone and not showing again. Also, you can't manage you dialog state.

Sometimes you need to implement a more complicated dialog with own logic, in that case, you need something like `DialogFragment` or `DialogController` in case of Conductor. `DialogController` it's like `Controller` that wrapping dialog, so you have all the features of `Controller`.

About #248. This implementation's not good enough for me, because of API (no support for the theme and styles e.t.), also not correct state handling and the bug with change handler.

**Comment by PaulWoitaschek** [comment]
@mradzinski What is "the bug with the change handler"

Thanks for releasing :tada:!

**Comment by MkhytarMkhoian** [comment]
@PaulWoitaschek @mradzinski  The bug in `.popChangeHandler(new SimpleSwapChangeHandler(false))`. Do not pass `false` into `SimpleSwapChangeHandler` because the view not removed.

return stub view in `onCreateView` method.
```
  return new View(getActivity());//stub view
```

**Comment by PaulWoitaschek** [comment]
And what issues does that cause?

**Comment by MkhytarMkhoian** [comment]
Stub view not remove from main ViewGroup container, so they left in the container until someone call removeAllViews() on a container.  In case of stub view, it's not dangerous, but not good anyway,  in some case, it may cause memory leaks, extra overdraw.

**Comment by MkhytarMkhoian** [comment]
@EricKuck HI, what about to link it to the main readme of this project?

**Comment by EricKuck** [comment]
Link added to the readme. Thanks!

**Comment by ursusursus** [comment]
Hi, this hides the view underneath for me when I call pushController, am I doing something wrong?

**Pull request closed without merging**
